### ISSUE TITLE
The first slide of the carrousel appears in white

### ISSUE THREAD

**Issue by davinchi7** [haztivity/hz-carousel#1]
When I implement the hz-carousel, it does not show me the content of the first slide, it appears in white, although if I navigate forward and then backwards if it appears. Can you help me, please?

**Comment by jperezdavinchi** [comment]
The haztivity page has a `display:none;` by default when is rendered and the elements inside have the height and with of 0.

Slick carousel uses the height of the images to resolve the container size, in this case, 0, that's the cause of not been visible.

We will resolve this soon, meanwhile, as solution is possible to refresh the slick size when the page has been shown using the shown event:

```typescript
import template from "./page.pug";
import {PageFactory, PageRegister, PageController} from "@haztivity/core";
import {HzCarouselResource} from "@haztivity/hz-carousel";
export let page: PageRegister = PageFactory.createPage(
    {
        title: "SomeTitle",
        name: "SomePage",
        resources: [
            HzAnimResource, 
            HzCarouselResource
        ],
        template: template
    }
);
page.on(
    PageController.ON_SHOWN, null, (eventObject, $page, $oldPage, oldPageRelativePosition, pageController) => {
        console.log(`${pageController.options.name} show end`);
       //Look for all the carousels in the page and refresh the positions
        $page.find("[data-resource='HzCarousel'").slick('setPosition');
    }
);
```
